### ISSUE TITLE
Disable inline styles appended to `<head>`

### ISSUE THREAD

**Issue by patrulea** [Shopify/buy-button-js#835]
**Is there a configuration key to disable inline styles appending to `<head>`?**

Every time BuyButton.js initializes it places a `<style>` element after my stylesheets, making it harder to override. I’d rather get rid of the tag entirely.

---

Contents of the `<style>` tag in question:

```css
.shopify-buy-modal-is-active {
  height: 100%;
  overflow: auto;
}

.shopify-buy-frame {
  display: inline-block
}

.shopify-buy-frame iframe {
    width: 100%;
    display: block;
    height: 0;
    overflow: hidden;
  }

.shopify-buy-frame--cart {
  width: 100%;
  max-width: 350px;
  position: fixed;
  top: 0;
  right: 0;
  height: 100%;
  z-index: 2147483647;
  transform: translateX(100%);
  -webkit-transform: translateX(100%);
  visibility: hidden
}

.shopify-buy-frame--cart iframe {
    height: 100%;
    display: none
  }

.shopify-buy-frame--cart iframe.is-block {
      display: block;
    }

.shopify-buy-frame--cart.is-initialized {
    -webkit-transition: -webkit-transform 250ms cubic-bezier(0.165, 0.84, 0.44, 1);
    transition: -webkit-transform 250ms cubic-bezier(0.165, 0.84, 0.44, 1);
    transition: transform 250ms cubic-bezier(0.165, 0.84, 0.44, 1);
    transition: transform 250ms cubic-bezier(0.165, 0.84, 0.44, 1), -webkit-transform 250ms cubic-bezier(0.165, 0.84, 0.44, 1);
  }

.shopify-buy-frame--cart.is-active {
    transform: translateX(0);
    -webkit-transform: translateX(0);
  }

.shopify-buy-frame--cart.is-visible {
    visibility: visible;
  }

.shopify-buy-frame--product {
  display: block
}

.shopify-buy-frame--product.shopify-buy__layout-horizontal {
    display: block;
    margin-left: auto;

    margin-right: auto
  }

.shopify-buy-frame--product.shopify-buy__layout-horizontal iframe {
      max-width: 100%
    }

@media (min-width: 950px) {

.shopify-buy-frame--product.shopify-buy__layout-horizontal iframe {
        max-width: 950px;
        margin-left: auto;
        margin-right: auto
    }
      }

.shopify-buy-frame--toggle {
  display: inline-block
}

.shopify-buy-frame--toggle:not(.is-sticky) {
    overflow: hidden;
    padding: 5px;
  }

.shopify-buy-frame--toggle.is-sticky {
    display: none;
    position: fixed;
    right: 0;
    top: 50%;
    transform: translateY(-50%);
    -webkit-transform: translateY(-50%);
    z-index: 2147483645;
  }

.shopify-buy-frame--toggle.is-active.is-sticky {
    display: block;
  }

.is-active .shopify-buy-frame--toggle iframe {
      min-height: 67px;
    }

.shopify-buy-frame--productSet {
  width: 100%;
}

.shopify-buy-frame--modal {
  position: fixed;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  z-index: 2147483646;
  display: none;
  -webkit-transition: background 300ms ease;
  transition: background 300ms ease
}

.shopify-buy-frame--modal iframe {
    height: 100%;
    width: 100%;
    max-width: none;
  }

.shopify-buy-frame--modal.is-active {
    background: rgba(0,0,0,0.6);
  }

.shopify-buy-frame--modal.is-block {
    display: block;
  }
```
